# -*- coding: utf-8 -*-
"""bank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0aIY6CK4thLbeIwyJFIJ0GHlVqUTtiP
"""

!pip install ucimlrepo

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from ucimlrepo import fetch_ucirepo
import seaborn as sns
from scipy.stats import chi2_contingency, ttest_ind
from scipy.stats import pointbiserialr

bank_marketing = fetch_ucirepo(id=222)

# data (as pandas dataframes)
X = bank_marketing.data.features
y = bank_marketing.data.targets

# variable information
bank_marketing.variables

df = pd.concat([X, y], axis=1)

df['pdays'].value_counts().head()

df['pdays']=df['pdays'].astype(int)
df['y'] = df['y'].map({'yes': 1, 'no': 0})

df['contacted_before'] = (df['pdays'] != -1).astype(int) #as 99% data will be skewed to show no variance hes p value will get affected
corr, p_val = pointbiserialr(df['contacted_before'], df['y'])
print(f"contacted_before | Corr = {corr:.3f} | p = {p_val:.5f}")

"""as p<5%, clients who were contacted before are more likely to subscribe than those who weren’t"""

df['job'].fillna(df['job'].mode()[0], inplace=True)
df['education']=df.groupby(['job'])['education'].transform(lambda x: x.fillna(x.mode()[0]) if not x.mode().empty else 'unknown')
df['contact'].fillna(0,inplace=True)
df['poutcome'].fillna('unknown',inplace=True)
# df['pdays'] = df['pdays'].replace(-1, 'None')

df['poutcome'].value_counts(normalize=True)

df.drop(columns=['duration'], inplace=True)

df1=df.copy()
for col in df1.select_dtypes(include='object').columns:
    mapping = {val: i for i, val in enumerate(df1[col].unique())}
    df1[col] = df1[col].map(mapping)

df1.corr(numeric_only=True)['y'].sort_values(ascending=False)

#but numeric corr for col like job can be inaccurate due to mapping, so :

for col in ['age', 'balance', 'campaign', 'previous']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

"""H0 (null hypothesis): There is no correlation between the numeric feature and y (the subscription result)."""

# for numerical using biserial corr:
from scipy.stats import pointbiserialr

for col in ['age', 'balance', 'campaign', 'previous']:
    corr, p_val = pointbiserialr(df[col], df['y'])
    print(f"{col:10} | Corr = {corr:.3f} | p = {p_val:.10f}")

for n in [100, 1000, 10000, 40000]:
    sample = df.sample(n, random_state=42)
    corr, p = pointbiserialr(sample['campaign'], sample['y'])
    print(f"n={n:5} → corr={corr:.3f}, p={p:.10f}")
#hygiene check, p drops as n increases

"""Statistically significant: All features show a non-random relationship with y.

Practically insignificant: Correlations < 0.1 mean weak linear relationships.
"""

# for categorical using cramer's v:
from scipy.stats import chi2_contingency

def cramers_v(x, y):
    confusion_matrix = pd.crosstab(x, y)
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    phi2 = chi2 / n
    r, k = confusion_matrix.shape
    return np.sqrt(phi2 / min(k - 1, r - 1))

for col in ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']:
    v = cramers_v(df[col], df['y'])
    print(f"{col:10} | Cramér’s V = {v:.3f}")

"""month and poutcome have moderate to high affect on y
and so does previous and pdays

**ML Model**
"""

# Split
X = df1.drop(columns=['y'])
y = df1['y']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# Train model with a balanced weight class as the skewness by no. of No's can make the model unbalannced
model = RandomForestClassifier(n_estimators=300, random_state=42)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
print(f"ROC-AUC Score: {roc_auc_score(y_test, y_prob):.3f}")

from xgboost import XGBClassifier
from sklearn.metrics import classification_report, roc_auc_score

# Handle imbalance with scale_pos_weight
scale = len(y_train[y_train == 0]) / len(y_train[y_train == 1])

xgb = XGBClassifier(
    random_state=42,
    scale_pos_weight=scale,
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='logloss'
)

# Train
xgb.fit(X_train, y_train)

# Predict
y_pred = xgb.predict(X_test)
y_prob = xgb.predict_proba(X_test)[:, 1]

# Evaluate
print(classification_report(y_test, y_pred))
print(f"ROC-AUC Score: {roc_auc_score(y_test, y_prob):.3f}")

from sklearn.metrics import ConfusionMatrixDisplay
ConfusionMatrixDisplay.from_estimator(xgb, X_test, y_test, cmap="Blues")

from sklearn.metrics import RocCurveDisplay
RocCurveDisplay.from_estimator(xgb, X_test, y_test)

import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score

thresholds = np.arange(0.1, 0.91, 0.1)

print(f"{'Threshold':<10} {'Precision':<10} {'Recall':<10} {'F1-score':<10}")
print("-"*45)

for t in thresholds:
    y_pred_t = (y_prob >= t).astype(int)
    p = precision_score(y_test, y_pred_t)
    r = recall_score(y_test, y_pred_t)
    f1 = f1_score(y_test, y_pred_t)
    print(f"{t:<10.2f} {p:<10.3f} {r:<10.3f} {f1:<10.3f}")

best_threshold=0.48

y_pred_opt = (y_prob >= best_threshold).astype(int)

from sklearn.metrics import classification_report, ConfusionMatrixDisplay
print(classification_report(y_test, y_pred_opt))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_opt, cmap="Blues")